from typing import Protocol

__all__ = ["MemoryReaderView", "MemoryReaderSource"]


class MemoryReaderSource(Protocol):
    def __len__(self) -> int: ...

    def __getitem__(self, key: slice) -> bytes: ...

    def close(self): ...


class MemoryReaderView(Protocol):
    def __bytes__(self) -> bytes: ...

    def __getitem__(self, key: slice) -> "MemoryReaderView": ...

    def __len__(self) -> int: ...

    def indices(self) -> slice: ...

    @property
    def source(self) -> MemoryReaderSource: ...
