[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "scrambleverse-vrmmetareader"
version = "0.3.1"

[tool.setuptools.packages.find]
exclude = ["tests"]
